### ISSUE TITLE
Additional information about infinality dependency

### ISSUE THREAD

**Issue by bozhodimitrov** [smerrill/fedora-21-openjdk8-infinality#1]
Hi,
I just want to ask you if you can add some additional information in the README file about how to install the infinality dependencies on Fedora 21 (I assume that you have that setup with this rpm package).

I found only a way to install the freetype-freeworld alternative and your RPM package doesn't detect that as a valid dependency (I guess that all infinality patches are also included into the freetype-freeworld package). So what I want to achieve is just to run patched OpenJDK on Fedora 21 with PyCharm (JetBrains).

Thanks in advance,
Best Regards
Jerry

**Comment by bozhodimitrov** [comment]
Also I just found this discussion: https://github.com/bohoomil/fontconfig-ultimate/issues/74
And it will be nice if you can add conditional dependency for this packages: https://www.copy.com/s/iFkCCIYj2gX1fW1E/fontconfig-infinality-ultimate/freetype

As far as I know @hadrons123 and @bohoomil maintain this whole thing (infinality-bundle). For now there is support for ArchLinux.

**Comment by robkli** [comment]
Hi, I also am interested in this project. I am not a developer so trying to do things with source is rather difficult. It appears the dependencies you mentioned by adding the repo descibed here: http://www.infinality.net/forum/viewtopic.php?f=2&t=77 are no longer available.

I use a tool daily that needs java and the terrible fonts are pretty unbearable. Thanks for any help!
